version: '3.8'

services:

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kartikdatabase
      MYSQL_USER: kartikuser
      MYSQL_PASSWORD: password
    ports:
      - "3300:3306"
    networks:
      - kartik-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    image: trialsmuz0r.jfrog.io/projectmibl/backned:${BACKEND_TAG}  
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: kartikuser
      DB_PASSWORD: password
      DB_NAME: kartikdatabase
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - kartik-network

  frontend:
    image: trialsmuz0r.jfrog.io/projectmibl/frontend:${FRONTEND_TAG}  
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - kartik-network

networks:
  kartik-network:

volumes:
  mysql-data:
